from django.urls import path

from . import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("projects/", views.ProjectListView.as_view(), name="project_list"),
    path("projects/create/", views.ProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/", views.ProjectDetailView.as_view(), name="project_detail"),
    path("projects/<int:pk>/edit/", views.ProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="project_delete"),
    path("projects/<int:pk>/state/", views.ProjectStateUpdateView.as_view(), name="project_state_update"),
    path("projects/<int:pk>/status/", views.ProjectStatusUpdateView.as_view(), name="project_status_update"),
    path("projects/<int:pk>/result/", views.ProjectResultUpdateView.as_view(), name="project_result_update"),
    path("projects/<int:pk>/progress/", views.ProjectProgressUpdateView.as_view(), name="project_progress_update"),
    path("projects/bulk/", views.BulkActionView.as_view(), name="bulk_action"),
    path("projects/assign/", views.AssignProjectsView.as_view(), name="assign_projects"),
    path("projects/export/", views.ExportProjectsView.as_view(), name="project_export"),
    path("tasks/", views.TaskListView.as_view(), name="task_list"),
    path("tasks/create/", views.TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("tasks/<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_update"),
    path("tasks/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
    path("tasks/<int:pk>/status/", views.TaskStatusUpdateView.as_view(), name="task_status_update"),
    path("tasks/<int:pk>/progress/", views.TaskProgressUpdateView.as_view(), name="task_progress_update"),
    path("import/", views.ImportExcelView.as_view(), name="import_excel"),
    path("imports/", views.ImportBatchListView.as_view(), name="import_list"),
    path("import/<int:pk>/", views.ImportDetailView.as_view(), name="import_detail"),
    path("import/<int:pk>/duplicates.xlsx", views.ImportDuplicateExportView.as_view(), name="import_duplicate_export"),
    path("kpi/", views.KPIView.as_view(), name="kpi"),
    path("reports/", views.ReportView.as_view(), name="reports"),
    path("logs/", views.ActivityLogListView.as_view(), name="activity_logs"),
    path("notifications/", views.NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", views.NotificationReadView.as_view(), name="notification_read"),
    path("notifications/read-all/", views.NotificationReadAllView.as_view(), name="notification_read_all"),
    path("settings/", views.GeneralSettingsView.as_view(), name="general_settings"),
    path("telegram/", views.TelegramSettingsView.as_view(), name="telegram_settings"),
    path("telegram/update/", views.TelegramSettingsUpdateView.as_view(), name="telegram_settings_update"),
    path("users/", views.UserListView.as_view(), name="user_list"),
    path("users/create/", views.UserCreateView.as_view(), name="user_create"),
    path("users/<int:pk>/edit/", views.UserUpdateView.as_view(), name="user_update"),
    path("api/projects/", views.ProjectListApiView.as_view(), name="api_project_list"),
    path("api/projects/<int:pk>/status/", views.ProjectUpdateStatusApiView.as_view(), name="api_project_status"),
    path("api/projects/<int:pk>/result/", views.ProjectUpdateResultApiView.as_view(), name="api_project_result"),
]
