# Generated by Django 5.2.15 on 2026-06-24 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PROJECT_ASSIGNED', 'Được giao dự án'), ('DEADLINE_UPDATED', 'Cập nhật hạn xử lý'), ('STATUS_UPDATED', 'Cập nhật trạng thái'), ('RESULT_UPDATED', 'Cập nhật kết quả'), ('PROJECT_OVERDUE', 'Quá hạn'), ('PROGRESS_UPDATED', 'Cập nhật tiến trình'), ('SYSTEM', 'Hệ thống')], default='SYSTEM', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status_note', models.TextField()),
                ('blocker_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Tạo dự án'), ('PROJECT_UPDATED', 'Cập nhật dự án'), ('PROJECT_DELETED', 'Xóa dự án'), ('PROJECT_ASSIGNED', 'Giao dự án'), ('STATUS_CHANGED', 'Đổi trạng thái'), ('RESULT_UPDATED', 'Cập nhật kết quả'), ('PROJECT_IMPORTED', 'Nhập dự án'), ('BULK_ACTION', 'Thao tác hàng loạt'), ('PROGRESS_UPDATED', 'Cập nhật tiến trình'), ('DEADLINE_UPDATED', 'Cập nhật hạn xử lý')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='wf_pr_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline_at'], name='wf_pr_deadline_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='workflow.project'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='wf_nt_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='wf_nt_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='wf_nt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='wf_nt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogress',
            index=models.Index(fields=['project'], name='wf_pg_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogress',
            index=models.Index(fields=['user'], name='wf_pg_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogress',
            index=models.Index(fields=['created_at'], name='wf_pg_created_idx'),
        ),
    ]
