# Generated by Django 5.2.15 on 2026-06-25 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_notification_projectprogress_assignment_deadline_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Tạo dự án'), ('PROJECT_UPDATED', 'Cập nhật dự án'), ('PROJECT_DELETED', 'Xóa dự án'), ('PROJECT_ASSIGNED', 'Giao dự án'), ('STATUS_CHANGED', 'Đổi trạng thái'), ('RESULT_UPDATED', 'Cập nhật kết quả'), ('PROJECT_IMPORTED', 'Nhập dự án'), ('BULK_ACTION', 'Thao tác hàng loạt'), ('PROGRESS_UPDATED', 'Cập nhật tiến trình'), ('DEADLINE_UPDATED', 'Cập nhật hạn xử lý'), ('TASK_CREATED', 'Tạo nhiệm vụ'), ('TASK_UPDATED', 'Cập nhật nhiệm vụ'), ('TASK_PROGRESS_UPDATED', 'Cập nhật tiến độ nhiệm vụ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_ASSIGNED', 'Được giao dự án'), ('TASK_ASSIGNED', 'Được giao nhiệm vụ'), ('DEADLINE_UPDATED', 'Cập nhật hạn xử lý'), ('STATUS_UPDATED', 'Cập nhật trạng thái'), ('RESULT_UPDATED', 'Cập nhật kết quả'), ('PROJECT_OVERDUE', 'Quá hạn'), ('PROGRESS_UPDATED', 'Cập nhật tiến trình'), ('TASK_PROGRESS_UPDATED', 'Cập nhật tiến độ nhiệm vụ'), ('SYSTEM', 'Hệ thống')], default='SYSTEM', max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=20)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Mới giao'), ('WORKING', 'Đang làm'), ('REVIEW', 'Chờ duyệt'), ('DONE', 'Hoàn thành'), ('OVERDUE', 'Quá hạn'), ('CANCELLED', 'Đã hủy')], default='NEW', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.task'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status_note', models.TextField()),
                ('blocker_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='workflow.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='wf_tk_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_by'], name='wf_tk_assigned_by_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='wf_tk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='wf_tk_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline_at'], name='wf_tk_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='wf_tk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogress',
            index=models.Index(fields=['task'], name='wf_tpg_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogress',
            index=models.Index(fields=['user'], name='wf_tpg_user_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogress',
            index=models.Index(fields=['created_at'], name='wf_tpg_created_idx'),
        ),
    ]
