# Generated by Django 5.2.15 on 2026-06-25 03:53

import secrets

from django.db import migrations, models


def populate_telegram_tokens(apps, schema_editor):
    User = apps.get_model("workflow", "User")
    for user in User.objects.filter(telegram_link_token__isnull=True):
        token = secrets.token_urlsafe(24)
        while User.objects.filter(telegram_link_token=token).exists():
            token = secrets.token_urlsafe(24)
        user.telegram_link_token = token
        user.save(update_fields=["telegram_link_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255)),
                ('bot_username', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('last_update_id', models.BigIntegerField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram settings',
                'verbose_name_plural': 'Telegram settings',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(populate_telegram_tokens, migrations.RunPython.noop),
    ]
