# Generated by Django 5.2.15 on 2026-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_telegramsettings_notification_telegram_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_state',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('KEY_BANNED', 'Cấm key'), ('AF_LOCKED', 'Khoá Af'), ('PAUSED', 'Tạm dừng')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_state'], name='wf_pr_state_idx'),
        ),
    ]
